# Generated by Django 3.2.10 on 2024-02-15 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('studentName', models.TextField()),
                ('oceanRegisterNo', models.TextField(unique=True)),
                ('mobileNumber', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('languageName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='McqListDatatModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mcqName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
                ('dob', models.DateTimeField()),
                ('mobileNumber', models.TextField()),
                ('address', models.TextField()),
                ('qualification', models.TextField()),
                ('nationality', models.TextField()),
                ('workingDesignation', models.TextField()),
                ('studentCollegeName', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsappNumber', models.TextField()),
                ('gender', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('age', models.IntegerField()),
                ('mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topicName', models.TextField()),
                ('languageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answeredQuestions', djongo.models.fields.JSONField()),
                ('result', models.IntegerField()),
                ('level', models.TextField()),
                ('languageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languagemodel')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topicmodel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', djongo.models.fields.JSONField()),
                ('level', models.TextField()),
                ('mark', models.IntegerField()),
                ('time', models.IntegerField()),
                ('languageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languagemodel')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topicmodel')),
            ],
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='mcqId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mcqlistdatatmodel'),
        ),
    ]
