# basic of Java
basicJava={"questions":
 [
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Who invented Java Programming?",
"code":"",
"option":["Guido van Rossum","James Gosling","Dennis Ritchie","Bjarne Stroustrup"],
"answer":"James Gosling"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the purpose of Java?",
"code":"",
"option":["To brew coffee","To develop desktop applications","To build dynamic web pages","To create software that runs on various platforms"],
"answer":"To create software that runs on various platforms"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the main characteristic of Java that makes it suitable for developing cross-platform applications?",
"code":"",
"option":["Platform dependence","Platform independence","Platform interdependence","Platform variability"],
"answer":"Platform independence"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What are the two main components of Java?",
"code":"",
"option":["Java Virtual Machine (JVM) and Java Development Kit (JDK)","Java Compiler and Java Interpreter","Java Runtime Environment (JRE) and JavaFX","Java API and JavaFX"],
"answer":"Java Virtual Machine (JVM) and Java Development Kit (JDK)"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the Java Development Kit (JDK)?",
"code":"",
"option":["A tool for debugging Java code","A collection of libraries for Java development","An integrated development environment (IDE)","A set of tools for compiling, debugging, and running Java code"],
"answer":"A set of tools for compiling, debugging, and running Java code"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the Java Virtual Machine (JVM)?",
"code":"",
"option":["A physical machine used to develop Java applications","An emulator for running Java applications on mobile devices","A software implementation that provides a runtime environment for Java bytecode","A tool for optimizing Java code performance"],
"answer":"A software implementation that provides a runtime environment for Java bytecode"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following is not a feature of Java?",
"code":"",
"option":["Platform independence","Automatic memory management","Multiple inheritance","Object-oriented programming"],
"answer":"Multiple inheritance"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is bytecode in Java?",
"code":"",
"option":["Machine code generated by the JVM","Intermediate code generated by the Java compiler","Low-level code written in Java","Code used for encryption in Java applications"],
"answer":"Intermediate code generated by the Java compiler"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the entry point for a Java program?",
"code":"",
"option":["Main method","Start method","Begin method","Init method"],
"answer":"Main method"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which tool is used to compile Java source code?",
"code":"",
"option":["javac","java","javadoc","jar"],
"answer":"javac"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the syntax for a single-line comment in Java?",
"code":"",
"option":["// This is a comment","/* This is a comment */","<!-- This is a comment -->","''' This is a comment '''"],
"answer":"// This is a comment"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the main advantage of using an IDE for Java development?",
"code":"",
"option":["Better performance","Platform independence","Enhanced code editing features","Higher security"],
"answer":"Enhanced code editing features"
},
"level":"beginner",
"mark":1,
"time":1
}
,{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which statement best describes the Java programming language?",
"code":"",
"option":["Compiled language","Interpreted language","Both compiled and interpreted","None of the above"],
"answer":"Both compiled and interpreted"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which part of the JDK contains tools such as javac and java?",
"code":"",
"option":["JRE (Java Runtime Environment)","JVM (Java Virtual Machine)","JAR (Java Archive)","JDK (Java Development Kit)"],
"answer":"JDK (Java Development Kit)"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following is true about Java comments?",
"code":"",
"option":["Comments are executed by the Java compiler.","Comments are ignored by the Java compiler.","Comments are used to indicate errors in the code.","Comments are used to specify the author of the code."],
"answer":"Comments are ignored by the Java compiler."
},
"level":"beginner",
"mark":1,
"time":1
}
]}
print(len(basicJava['questions']))

# 
variableDatatypes={
    "questions":[
        {
"languageId":1,
"topicId":2,
"questions":{
"question":"Which of the following is not a valid data type in Java?",
"code":"",
"option":["int","string","float","boolean"],
"answer":"string"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the default value of a boolean variable in Java?",
"code":"",
"option":["true","false","null","0"],
"answer":"false"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"\nint x = 5;\nSystem.out.println(++x);",
"option":["4","5","6","Error"],
"answer":"6"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"Which of the following is not a valid identifier in Java?",
"code":"",
"option":["my_variable","_myVariable","123identifier","$myVariable"],
"answer":"123identifier"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"int a = 5, b = 10;\nSystem.out.println(\"The sum is \" + (a + b));",
"option":["The sum is 15","The sum is 510","The sum is 5 + 10","Error"],
"answer":"The sum is 15"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":2,
"questions":{
"question":"Which data type is used to store a single character in Java?",
"code":"",
"option":["char","int","string","boolean"],
"answer":"char"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the range of values that can be stored in a 'byte' data type in Java?",
"code":"",
"option":["-128 to 127","-32768 to 32767","-2^31 to 2^31-1","0 to 65535"],
"answer":"-128 to 127"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"\nint x = 5 / 2;\nSystem.out.println(x);",
"option":["2.5","2","3","Error"],
"answer":"2"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"Which data type is used to store decimal numbers with single precision in Java?",
"code":"",
"option":["int","double","float","long"],
"answer":"float"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the output of the following code snippet?\ndouble d = 10.5;\nSystem.out.println(d);",
"code":"",
"option":["10","10.0","10.5","Error"],
"answer":"10.5"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the value of 'x' after executing the following code snippet?",
"code":"\nint x = 10;\nx += 5;",
"option":["5","10","15","Error"],
"answer":"15"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":2,
"questions":{
"question":"Which data type is used to store true/false values in Java?",
"code":"",
"option":["int","boolean","char","double"],
"answer":"boolean"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":2,
"questions":{
"question":"Which data type is used to store large whole numbers in Java?",
"code":"",
"option":["int","float","double","long"],
"answer":"long"
},
"level":"beginner",
"mark":1,
"time":1
},
{
"languageId":1,
"topicId":2,
"questions":{
"question":"Which data type is used to store a single bit value in Java?",
"code":"",
"option":["byte","short","boolean","char"],
"answer":"boolean"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":2,
"questions":{
"question":"What is the value of 'x' after executing the following code snippet?\nint x = 10;\nx *= 2;",
"code":"",
"option":["5","10","20","Error"],
"answer":"20"
},
"level":"beginner",
"mark":1,
"time":1
}
    ]
}

print(len(variableDatatypes["questions"]))


# java beginner I

javaBeginner1={"questions":[

{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"String str = \"Hello\";\nSystem.out.println(str.substring(2, 4));",
"option":["a) Hel","b) lo","c) ell","d) llo"],
"answer":"c) ell"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following is not a valid access specifier in Java?",
"code":"",
"option":["a) public","b) protected","c) private","d) package"],
"answer":"d) package"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What does the \"break\" statement do in Java?",
"code":"",
"option":["a) Exits the loop or switch statement","b) Continues to the next iteration of the loop","c) Skips the current iteration of the loop","d) None of the above"],
"answer":"a) Exits the loop or switch statement"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following is not a valid loop in Java?",
"code":"",
"option":["a) for","b) foreach","c) while","d) do-while"],
"answer":"b) foreach"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"int i = 10;\nSystem.out.println(i++);",
"option":["a) 10","b) 11","c) 12","d) Compile error"],
"answer":"a) 10"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"System.out.println(Math.min(Double.MIN_VALUE, 0.0));",
"option":["a) Double.MIN_VALUE","b) 0.0","c) 0.0 (negative)","d) 0.0 (positive)"],
"answer":"b) 0.0"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"System.out.println(10 + 20 + \"Hello\");",
"option":["a) 30Hello","b) 1020Hello","c) Compile error","d) Runtime error"],
"answer":"a) 30Hello"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following is not a Java keyword?",
"code":"",
"option":["a) sizeof","b) instanceof","c) native","d) transient"],
"answer":"a) sizeof"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"System.out.println(\"5\" + 3 + 2);",
"option":["a) 532","b) 10","c) 5+3+2","d) Compile error"],
"answer":"a) 532"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following is used to create an object in Java?",
"code":"",
"option":["a) new","b) class","c) create","d) instanceOf"],
"answer":"a) new"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"System.out.println(5 == 5.0);",
"option":["a) true","b) false","c) Compile error","d) Runtime error"],
"answer":"a) true"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"System.out.println(10 % 3);",
"option":["a) 1","b) 2","c) 3","d) 0"],
"answer":"a) 1"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"Which of the following statements is true about interfaces in Java?",
"code":"",
"option":["a) Interfaces can have constructors.","b) Interfaces can have method definitions.","c) Interfaces can extend classes.","d) Interfaces can have instance variables."],
"answer":"b) Interfaces can have method definitions."
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the output of the following code snippet?",
"code":"System.out.println(\"abc\".toUpperCase());",
"option":["a) abc","b) ABC","c) Compile error","d) Runtime error"],
"answer":"b) ABC"
},
"level":"beginner",
"mark":1,
"time":1
}
,
{
"languageId":1,
"topicId":1,
"questions":{
"question":"What is the correct way to declare a string variable in Java?",
"code":"",
"option":["a) string s;","b) String s;","c) string s = "";","d) String s = "";"],
"answer":"d) String s = "";"
},
"level":"beginner",
"mark":1,
"time":1
}]}

print(len(javaBeginner1['questions']))

# Control Flow (if, else, switch)
ControlFlow={
    "questions":[
        
{
"languageId":1,
"topicId":3,
"questions":{
"question":"What is the syntax for an if statement in Java?",
"code":"",
"option":["if condition { // code block }","if (condition) { // code block }","if { // code block } condition","condition { // code block } if"],
"answer":"if (condition) { // code block }"
},
"level":"beginner",
"mark":1,
"time":1
},{
"languageId":1,
"topicId":3,
"questions":{
"question":"What will be the output of the following code snippet?",
"code":"\nint x = 10;\nif (x > 5) {\n System.out.println(\"x is greater than 5\");\n}",
"option":["x is greater than 5","x is less than 5","No output","Error"],
"answer":"x is greater than 5"
},
"level":"beginner",
"mark":1,
"time":1
}
    ]
}